name: CI

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:6.0
                ports:
                    - 27017:27017

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
              env:
                  MONGODB_URI: mongodb://localhost:27017/Twitter
